---
title: "Eval Static Analysis"
author: "Chakshu Goyal"
date: "07/06/2018"
output:
  html_document: default
  pdf_document: default
---

## 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(tools)
```

## Load the data
Usage of the function eval in R-packages
```{r}
evaldf <- read_csv("evals.csv")
```

## Plot occurences of evals in packages
```{r one}
# Occurences of evals in each package plot
ggplot(evaldf , aes(pkg)) + geom_bar() + theme(axis.text.x = element_blank()) + labs(y="Number of evals", x="packages", title="Figurative distribution of the usage of eval in various packages")

# No. of occurences of eval in each package table
evalCntPerPkg <- plyr::count(evaldf , "pkg")
knitr::kable(head(arrange(evalCntPerPkg, desc(freq)) , 20) , col.names = c("Package" , "Number of evals"))

#plot histogram for number of projects vs number of evals
ggplot(evalCntPerPkg, aes(freq)) + geom_density()+ scale_x_log10() + labs(y="Number of projects (density)", x="Number of Evals - (log scaled)", title="Evals distribution in the packages")
ggplot(evalCntPerPkg , aes(freq)) + geom_histogram(bins=50) + scale_x_log10() + labs(y="Number of projects", x="Number of Evals", title="Evals distribution in the packages - histogram")
ggplot(evalCntPerPkg , aes(freq)) + geom_boxplot() + labs(y="Number of Evals", x="Packages", title="Evals distribution in the packages - boxplot")

# Eval occurences per use
knitr::kable(plyr::count(evaldf , "use") , col.names = c("Usage" , "Frequency"))

knitr::kable(tribble(
  ~A,~B,
  "Total Number of packages considered" , "12574",
  "Number of packages using eval" , nrow(unique.data.frame(evaldf["pkg"]))
))

```

##Interesting plots 
```{r two}
#Files using most evals
evalCountPerFile <- plyr::count(evaldf , "path")
knitr::kable(head(arrange(evalCountPerFile, desc(freq)), 10))

#write_csv( select(evaldf,path), "paths.csv")
#cat paths.csv | while read line ; do cloc $line | grep -o "[0-9]*$" >> "lines.txt" ; done

#plot number of evals vs number of lines in files
lineCountPerFile <- 
  evaldf %>%
    group_by(path) %>%
      summarise(lineCount = first(lineCount), charCount = first(charCount), pkg = first(pkg))

lineNdEvalCountPerFile <- merge(lineCountPerFile , evalCountPerFile)
ggplot(data = lineNdEvalCountPerFile, mapping = aes(x = lineCount, y = freq)) + geom_point() + labs(y="Number of Evals", x="Number of lines", title="Eval usage per lines in files")
ggplot(data = lineNdEvalCountPerFile, mapping = aes(x = charCount, y = freq)) + geom_point() + labs(y="Number of Evals", x="Number of chars", title="Eval usage per char in files")

#plot number of evals vs number of lines in pkgs
lineCountPerPkg <- 
  lineCountPerFile %>%
    group_by(pkg) %>%
      summarise(lineCount = sum(lineCount), charCount = sum(charCount))
lineNdEvalCountPerPkg <- merge(lineCountPerPkg, evalCntPerPkg)
ggplot(data = lineNdEvalCountPerPkg, mapping = aes(x = lineCount, y = freq)) + geom_point() + labs(y="Number of Evals", x="Number of lines", title="Eval usage per lines in packages")
ggplot(data = lineNdEvalCountPerPkg, mapping = aes(x = charCount, y = freq)) + geom_point() + labs(y="Number of Evals", x="Number of chars", title="Eval usage per char in packages")
```

## Eval occurences in folders inside of packages
```{r three}
#print(evaldf)
#evaldf <- mutate(evaldf , folder = strsplit(path,"/")[7] )
evaldf <- 
  evaldf %>% 
    rowwise() %>% 
      mutate(folder = strsplit(path, split="/")[[1]][7] ,extension = file_ext(path)  )

evalCntPerFolder <- plyr::count(evaldf , "folder")
knitr::kable(head(arrange(evalCntPerFolder, desc(freq)) , 20) , col.names = c("Folder" , "Number of evals"))
ggplot(evalCntPerFolder , aes(freq)) + geom_histogram(bins=50) + scale_x_log10() + labs(y="Number of Folders", x="Number of Evals", title="Evals distribution in the folders - histogram")

evalCntPerExtension <- plyr::count(evaldf , "extension")
knitr::kable(head(arrange(evalCntPerExtension, desc(freq)) , 10) , col.names = c("File Type  " , "Number of evals"))

```
